### ISSUE TITLE
yelp数据集“business_id”报错

### ISSUE THREAD

**Issue by loredunk** [RUCAIBox/NCL#26]
跑yelp数据集  装载完Config提示信息之后，报了以下错误
Traceback (most recent call last):
  File "main_ncl_all.py", line 75, in <module>
    run_single_model(args)
  File "main_ncl_all.py", line 30, in run_single_model
    dataset = create_dataset(config)
  File "/home/chengang/.conda/envs/kaggle/lib/python3.7/site-packages/recbole/data/utils.py", line 68, in create_dataset
    dataset = dataset_class(config)
  File "/home/chengang/.conda/envs/kaggle/lib/python3.7/site-packages/recbole/data/dataset/dataset.py", line 96, in __init__
    self._from_scratch()
  File "/home/chengang/.conda/envs/kaggle/lib/python3.7/site-packages/recbole/data/dataset/dataset.py", line 108, in _from_scratch
    self._data_processing()
  File "/home/chengang/.conda/envs/kaggle/lib/python3.7/site-packages/recbole/data/dataset/dataset.py", line 151, in _data_processing
    self._data_filtering()
  File "/home/chengang/.conda/envs/kaggle/lib/python3.7/site-packages/recbole/data/dataset/dataset.py", line 173, in _data_filtering
    self._filter_nan_user_or_item()
  File "/home/chengang/.conda/envs/kaggle/lib/python3.7/site-packages/recbole/data/dataset/dataset.py", line 637, in _filter_nan_user_or_item
    dropped_inter = self.inter_feat.index[self.inter_feat[field].isnull()]
  File "/home/chengang/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/chengang/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'business_id'

**Comment by hyp1231** [comment]
你好！可能是由于配置文件和数据集文件不对应导致的。我们前阵子更新了云存储中的数据集，可能造成了一些不一致，您可以参考 https://github.com/RUCAIBox/NCL/commit/0aaf7c8d5a1036d9493c47b5cb6888ca20c814a9 这个 commit 来调整一下 `yelp.yaml` 这个文件，应该就可以解决这个问题。
