### ISSUE TITLE
Quick Start报数据集错误

### ISSUE THREAD

**Issue by gongkaiqi** [RUCAIBox/NCL#39]
运行：python main.py --dataset ml-1m

请问下面的报错是什么原因呢，为什么不能自动导入数据集呢：
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    run_single_model(args)
  File "main.py", line 28, in run_single_model
    dataset = create_dataset(config)
  File "/home/kq/anaconda3/envs/KGAT-Pytorch/lib/python3.6/site-packages/recbole/data/utils.py", line 55, in create_dataset
    return Dataset(config)
  File "/home/kq/anaconda3/envs/KGAT-Pytorch/lib/python3.6/site-packages/recbole/data/dataset/dataset.py", line 98, in __init__
    self._from_scratch()
  File "/home/kq/anaconda3/envs/KGAT-Pytorch/lib/python3.6/site-packages/recbole/data/dataset/dataset.py", line 108, in _from_scratch
    self._load_data(self.dataset_name, self.dataset_path)
  File "/home/kq/anaconda3/envs/KGAT-Pytorch/lib/python3.6/site-packages/recbole/data/dataset/dataset.py", line 211, in _load_data
    self._load_inter_feat(token, dataset_path)
  File "/home/kq/anaconda3/envs/KGAT-Pytorch/lib/python3.6/site-packages/recbole/data/dataset/dataset.py", line 232, in _load_inter_feat
    raise ValueError(f'File {inter_feat_path} not exist.')
ValueError: File dataset/ml-1m/ml-1m.inter not exist.

**Comment by hyp1231** [comment]
感谢关注我们的工作，请问您 recbole 的版本是 1.0.1 吗

**Comment by gongkaiqi** [comment]
我的recbole是0.2.1，换为1.0.1后可以成功下载数据集了（备注：1.0.1要求scipy为1.6.0，我原先python3.6的环境，好像因为3.6的python不能匹配recbole1.0.1所要求的scipy1.6.0，所以我创建了python3.7的新环境来安装recbole1.0.1）
