### ISSUE TITLE
about the distribution of item embeddings

### ISSUE THREAD

**Issue by FinchNie** [RUCAIBox/NCL#8]
Hi, thanks for your great work. 
I am confused about Figure 6 when reading this paper.
> We plot item embedding distributions with Gaussian kernel density estimation (KDE) in two-dimensional space
![image](https://user-images.githubusercontent.com/62511842/164035491-63aaee3e-b67a-4023-b0a2-0af9b3502d88.png)

Are codes for this figure available? Thank you.

**Comment by hyp1231** [comment]
Hi,

We firstly train models with `--embedding_size=2`, then

```python
import torch.nn.functional as F
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from recbole.quick_start import load_data_and_model


filepath = 'path/to/your/model'  # replace this to your path

config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
    model_file=filepath,
)

item_emb = model.item_embedding.weight.cpu().detach()
item_emb = F.normalize(item_emb, dim=1).numpy()
print(item_emb.shape)

plt.figure(figsize=(3, 3))

df = pd.DataFrame({
    'x': item_emb.T[0],
    'y': item_emb.T[1]
})

ax = sns.kdeplot(
    data=df, x='x', y='y',
    thresh=0, levels=300, cmap=sns.color_palette('light:b', as_cmap=True)
)

plt.xlabel('')
plt.ylabel('')

plt.tight_layout()
plt.savefig('your pdf file name', format='pdf', dpi=300)  # replace this to your path
plt.show()
```

**Comment by hyp1231** [comment]
Closing due to inactivity. Please comment if you're still having issues.

**Comment by Rvlis** [comment]
你好，请问我用你提供的方法但是报这个错误是怎么回事呢？
`Traceback (most recent call last):
  File "visualization.py", line 11, in <module>
    model_file=filepath,
  File "/home/rvlis/anaconda3/envs/NCL/lib/python3.7/site-packages/recbole/quick_start/quick_start.py", line 149, in load_data_and_model
    model = get_model(config['model'])(config, train_data.dataset).to(config['device'])
  File "/home/rvlis/anaconda3/envs/NCL/lib/python3.7/site-packages/recbole/utils/utils.py", line 74, in get_model
    raise ValueError('`model_name` [{}] is not the name of an existing model.'.format(model_name))
ValueError: `model_name` [NCL] is not the name of an existing model.`

**Comment by Rvlis** [comment]
这是训练的模型路径`filepath = './saved/NCL-Jun-01-2022_20-55-28.pth'  # replace this to your path`

**Comment by Rvlis** [comment]
```
Traceback (most recent call last):
  File "visualization.py", line 11, in <module>
    model_file=filepath,
  File "/home/rvlis/anaconda3/envs/NCL/lib/python3.7/site-packages/recbole/quick_start/quick_start.py", line 149, in load_data_and_model
    model = get_model(config['model'])(config, train_data.dataset).to(config['device'])
  File "/home/rvlis/anaconda3/envs/NCL/lib/python3.7/site-packages/recbole/utils/utils.py", line 74, in get_model
    raise ValueError('`model_name` [{}] is not the name of an existing model.'.format(model_name))
ValueError: `model_name` [NCL] is not the name of an existing model.
```

**Comment by hyp1231** [comment]
您可以把从 RecBole 加载的 `load_data_and_model` 这个函数替换成下面这个函数试试

```python
from ncl import NCL

def load_data_and_model(model_file):
    checkpoint = torch.load(model_file)
    config = checkpoint['config']
    init_seed(config['seed'], config['reproducibility'])
    init_logger(config)
    logger = getLogger()
    logger.info(config)

    dataset = create_dataset(config)
    logger.info(dataset)
    train_data, valid_data, test_data = data_preparation(config, dataset)

    init_seed(config['seed'], config['reproducibility'])
    model = NCL(config, train_data.dataset).to(config['device'])
    model.load_state_dict(checkpoint['state_dict'])
    model.load_other_parameter(checkpoint.get('other_parameter'))

    return config, model, dataset, train_data, valid_data, test_data
```
